### ISSUE TITLE
Novo portal do DeCS - Sugestão

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#1]
Fábio,

Sugestão de navegabilidade: ao mostrar o resultado da busca, sugiro manter o elemento procurado no campo "search" / "búsqueda" / "pesquisa" / "recherche".

**Comment by falbrito** [comment]
O elemento pesquisa é mantido no resultado da busca
![image](https://user-images.githubusercontent.com/6940371/80372286-b3efc400-8869-11ea-9185-c6fc0de770af.png)
