### ISSUE TITLE
Criar links para descritores nos textos de notas de escopo e indexação

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#100]
Colocar hiperlinks nos termos nas notas de escopo e de indexação que forem descritores ou termos alternativos. 
Exemplo:

Nota de escopo do descritor **Astenia Neurocirculatória**:
Síndrome clínica caracterizada por palpitação, FALTA DE AR, respiração difícil, reclamações subjetivas de esforço e desconforto, tudo após um ESFORÇO FÍSICO leve. Outros sintomas podem ser TONTURAS, tremores, SUDORESE e INSÔNIA. A astenia neurocirculatória é tipicamente mais vista como uma forma de transtorno de ansiedade.

Nos termos em letras capitalizadas, colocar links para seus respectivos descritores.

Agradecemos!
Ana e @lucianaPRB

**Comment by wilsonmoura** [comment]
Relacionado com bireme/fi-admin#1073

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
@wilsonmoura Muito bom, obrigada! 
Peço apenas para fazer a página do descritor sensibilizado na nota de escopo abrir em outra aba.

**Comment by wilsonmoura** [comment]
@acecampos normalmente, somente os links externos devem abrir em outra aba. Como esses links remetem para o próprio site, o padrão é manter a navegação na mesma aba. Se mesmo assim for necessário esse ajuste, favor confirmar para que possamos avançar com essa atividade.

**Comment by acecampos** [comment]
Ok, @wilsonmoura se é padrão, então é melhor não mexer. Agradeço muito! Validado no ambiente de teste do portal.
