### ISSUE TITLE
Mudar nome de categoria VS

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#101]
Por favor, @wilsonmoura e @viniciusandrade, mudar o nome da categoria Vigilância Sanitária para VIGILÂNCIA EM SAÚDE, com base em documentação descrita em https://paho.sharepoint.com/:b:/r/sites/BIR/TC/TC/Processos/Terminologias/DeCS/Categorias%20exclusivas/VS/Email%20%E2%80%93%20VS-2008.pdf?csf=1&web=1&e=FLRM1H

EN: Surveillance in Public Health
PT-BR: Vigilância em Saúde
ES: Vigilancia de la Salud
FR: Surveillance de la santé publique

Obrigada!

Agradecemos,
Ana e @lucianaPRB

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor realizar os devidos ajustes no serviço [Localizar descritor de assunto](https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt) disponível no Portal de Pesquisa da BVS.

**Comment by wilsonmoura** [comment]
@acecampos @lucianaPRB abrimos um issue no projeto do iAHx para realizar os devidos ajustes no serviço [Localizar descritor de assunto](https://pesquisa.bvsalud.org/portal/decs-locator/?lang=pt) disponível no Portal de Pesquisa da BVS.

Segue link do respectivo issue: bireme/iahx-opac/issues/331

Sendo assim, vamos encerrar esse issue, pois já realizamos os ajustes necessários no Portal DeCS.
