### ISSUE TITLE
Permitir a busca por termos de es-es no site

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#104]
Hoje, no site do DeCS, não é permitida a busca por termo em espanhol da Espanha.
Exemplo:
MH: factor 4 de tipo Kruppel
DUI: D000090062

Agradecemos!
Ana e @lucianaPRB

**Comment by wilsonmoura** [comment]
Incluir os campos abaixo no índice Solr:

    ths_mh_eses
    ths_mh_et_eses
    ths_pep_eses
    ths_pep_et_eses
    ths_permuted_eses

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados no script de processamento que gera o arquivo XML usado no índice Solr do Portal DeCS.

Localização do arquivo: `serverofi5:/bases/dec.000/cria_indice_solr/tpl/cria_xml_solr.py`

Vale ressaltar que a validação dessa demanda só poderá ser feita assim que a atividade de atualização do índice de pesquisa do Portal DeCS para o próximo lançamento da versão do DeCS estiver concluída.

**Comment by acecampos** [comment]
@wilsonmoura muito obrigada!
