### ISSUE TITLE
ID no tesauro 13035 não recupera resultado no decs.bvsalud.org por usuário externo

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#107]
@wilsonmoura, aconteceu a seguinte situação:

Usuário externo contatou @lucianaPRB informando que não recupera o registro do descritor "Tecnologia Assistiva" no site decs.bvsalud.org.

- Usuários na BIREME (@marcoslmori e @acecampos) recuperaram o termo.
- Usuários fora da BIREME (@lucianaPRB e @acecampos) não recuperam o termo. 

Pesquisa com assis* ou assis$ ou com um dos termos alternativos: o termo aparece na lista alfabética, mas o registro não abre: 

![image](https://user-images.githubusercontent.com/35345406/215229135-4ace8eba-5260-4b04-ad8c-7a659793f9dc.png)

Resumindo:
Para usuário fora da BIREME, 
- https://decs.bvsalud.org/ths/resource/?id=13035 => não traz resultado
- [https://decs.bvsalud.org/ths/?pmt=swapped&filter=ths_termall&q=assis*](https://decs.bvsalud.org/ths/?pmt=swapped&filter=ths_termall&q=assis*) => lista o termo, mas não abre o registro.

Agradeço!

**Comment by wilsonmoura** [comment]
@acecampos para resolver esse problema, fizemos a limpeza do cache desse registro no Portal DeCS. Favor validar.

**Comment by acecampos** [comment]
Obrigada, @wilsonmoura. Validado.
