### ISSUE TITLE
Redirect de páginas antigas do DeCS para o portal atual

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/thesaurus-wp-plugin#108]
Prezado @viniciusandrade 
Por favor, criar redirecionamento automático das páginas do DeCS https://decs.bvs.br/E/homepagee.htm, es, e https://decs.bvs.br/I/homepagei.htm, eng. para as páginas atuais, respectivamente, https://decs.bvsalud.org/es/ e https://decs.bvsalud.org/en/.

Agradecemos,
Luciana e @acecampos

**Comment by viniciusandrade** [comment]
Prezada @lucianaPRB 
Redirecionamento realizado, quando possível favor validar.
Obrigado

**Comment by lucianaPRB** [comment]
Prezado @viniciusandrade 
Confirmo o funcionamento dos links. Obrigada
