### ISSUE TITLE
ID D000784 não recupera resultado no Portal DeCS

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/thesaurus-wp-plugin#109]
Prezado Wilson,
O Descritor **Aneurisma Dissecante** apresentou problema semelhante ao do issue #107 

![image](https://user-images.githubusercontent.com/93340661/217614004-67ba40f7-f6ee-4936-943e-aab3966f0274.png)

![image](https://user-images.githubusercontent.com/93340661/217614078-001ea0e6-a418-42db-9880-779b67262642.png)

Poderia verificar, por favor?
Muito obrigada!
c/c @acecampos

**Comment by wilsonmoura** [comment]
@lucianaPRB para resolver esse problema, fizemos a limpeza do cache desse registro no Portal DeCS. Favor validar.

**Comment by lucianaPRB** [comment]
Validado! Obrigada @wilsonmoura
