### ISSUE TITLE
Erro na recuperação - descritor Webcast

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#110]
https://decs.bvsalud.org/ths/resource/?id=53829&filter=ths_termall&q=webcast
@wilsonmoura parece mais um problema de cache.
Poderia, por favor, arrumar?
Obrigada!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Validado. Obrigada, @wilsonmoura!
