### ISSUE TITLE
Erro na recuperação - descritor Abbreviations as Topic

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#111]
https://decs.bvsalud.org/ths/resource/?id=4&filter=ths_termall&q=Abbreviations%20as%20Topic
@wilsonmoura parece mais um problema de cache.
Poderia, por favor, arrumar?
Obrigada!
@lucianaPRB e @acecampos

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Validado, @wilsonmoura. Agradeço!
