### ISSUE TITLE
Erro na recuperação - descritor Modelos Biológicos

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#112]
https://decs.bvsalud.org/ths/resource/?id=9144
@wilsonmoura parece mais um problema do cache.
Poderia, por favor, arrumar?
Muito obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Muito obrigada, @wilsonmoura!
Validado.
