### ISSUE TITLE
Erro na recuperação - descritor Farmacopeia Homeopática

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#113]
https://decs.bvsalud.org/ths/resource/?id=57870&filter=ths_termall&q=farmacop%C3%A9ia%20homeop%C3%A1tica
@wilsonmoura parece mais um problema do cache.
Poderia, por favor, arrumar?
Muito obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados, Favor validar?

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados, Favor validar.

**Comment by acecampos** [comment]
@wilsonmoura Obrigada! 
Validado.
