### ISSUE TITLE
Criar base congelada DeCS 2023

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/thesaurus-wp-plugin#114]
- [x] Abrir chamado ao ITI solicitando criação do banco de dados
- [x] No servidor de processamento, fazer o carregamento do dump no banco de produção
- [x] Alterar `app-env-dev `do ambiente de testes do FI-ADMIN direcionando para novo banco e realizar testes

**Comment by wilsonmoura** [comment]
Documentação: #28

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar o arquivo `app-env-dev` do ambiente de testes do FI-ADMIN com as configurações da nova base congelada (informações enviadas por e-mail).

**Comment by viniciusandrade** [comment]
@wilsonmoura ambiente de testes do FI-ADMIN atualizado com as configurações da base congelada DeCS 2023.

**Comment by wilsonmoura** [comment]
@acecampos base congelada do Portal DeCS 2023 atualizada no ambiente de testes. Favor validar.

**Comment by acecampos** [comment]
Validado, @wilsonmoura. Muito obrigada.

**Comment by wilsonmoura** [comment]
@viniciusandrade favor atualizar o arquivo `app-env-dev` do ambiente de produção do FI-ADMIN com as configurações da nova base congelada (informações enviadas por e-mail).

**Comment by viniciusandrade** [comment]
@wilsonmoura ambiente de produção atualizado.
