### ISSUE TITLE
Atualizar índice de pesquisa do Portal DeCS 2023

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/thesaurus-wp-plugin#115]

**Comment by wilsonmoura** [comment]
@acecampos a atualização do índice de pesquisa do Portal DeCS foi finalizada. Favor validar no ambiente de testes.

Documentação: https://wiki.bireme.org/intranet/index.php/Indexacao_solr_tesauro_decs

**Comment by acecampos** [comment]
@wilsonmoura Validado. Muito obrigada!
