### ISSUE TITLE
Erro na recuperação - descritor Virus del Papiloma Humano (Espanhol somente)

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#118]
https://decs.bvsalud.org/es/ths/resource/?id=60222&filter=ths_termall&q=virus%20del%20papiloma%20humano

@wilsonmoura mais um caso de cache. Foi reportado por usuário.

Quando possível, poderia ajustar, por favor?
Muito obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Validado; obrigada!
