### ISSUE TITLE
Erro na recuperação - descritor Galeopsis ochroleuca (inglês)

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#119]
https://decs.bvsalud.org/es/ths/resource/?id=60222&filter=ths_termall&q=virus%20del%20papiloma%20humano

@wilsonmoura parece mais um caso de cache, descritor em inglês.
Quando possível, poderia ajustar, por favor?
Muito obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Oi, @wilsonmoura! Ainda não está funcionando em inglês: https://decs.bvsalud.org/en/ths/resource/?id=26594

**Comment by wilsonmoura** [comment]
@acecampos favor testar novamente.

**Comment by acecampos** [comment]
Agora está funcionando. Validado. Obrigada!
