### ISSUE TITLE
Divergência entre páginas de idiomas diferentes

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#120]
@wilsonmoura, consultei o termo em português (https://decs.bvsalud.org/ths/resource/?id=59299) e em inglês (https://decs.bvsalud.org/en/ths/resource/?id=59299) e os descritores em português e francês estão diferentes entre as páginas na interface em inglês e francês. 

POR:
![image](https://user-images.githubusercontent.com/35345406/234035817-a53fd75b-ddee-4513-b08f-49f0620d1241.png)

 e 
ENG:
![image](https://user-images.githubusercontent.com/35345406/234035579-9feabf49-02bf-41b3-a9f3-9c31edf7766f.png)

O francês foi carregado em 11 de fevereiro de 2023, mas o português já estava alterado desde 13 de outubro de 2022:

![image](https://user-images.githubusercontent.com/35345406/234036603-4aa929f3-4ba5-4068-bf23-dd1a8d512758.png)

Poderia verificar o que ocorreu, por favor?
@lucianaPRB para seu conhecimento.
Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos para resolver esse problema, fizemos a limpeza do cache desse registro no Portal DeCS. Favor validar.

**Comment by acecampos** [comment]
Oi, @wilsonmoura! Na interface em francês, o problema ainda persiste: https://decs.bvsalud.org/fr/ths/resource/?id=59299.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Obrigada! Validado.
