### ISSUE TITLE
Erro na recuperação - descritor id=33246 em francês e inglês

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#122]
Boa tarde, @wilsonmoura!

Parece mais um caso de cache.
Por favor, poderia verificar?

https://decs.bvsalud.org/fr/ths/resource/?id=33246&filter=ths_termall&q=aula 
https://decs.bvsalud.org/en/ths/resource/?id=33246&filter=ths_termall&q=aula

Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Validado!
Obrigada, Wilson!
