### ISSUE TITLE
Erro na recuperação - descritor id=14382 em inglês

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#123]
Boa tarde, @wilsonmoura! 
Acho que é mais um caso de cache. Pode verificar, por favor?

https://decs.bvsalud.org/en/ths/resource/?id=14382&filter=ths_exact_term&q=time

Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Validado! Obrigada!
