### ISSUE TITLE
Erro na recuperação - descritor id=26389 em português

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#124]
Olá, Wilson.
https://decs.bvsalud.org/ths/resource/?id=26389&filter=ths_exact_term&q=Cuphea%20viscosissima
Parece ser caso de cache. 
Você poderia verificar, por favor?
Grata!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar.

**Comment by acecampos** [comment]
Validado. Obrigada!
