### ISSUE TITLE
Erro de recuperação no portal decs.bvsalud.org

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#126]
Olá, Wilson.
https://decs.bvsalud.org/ths?filter=ths_termall&q=assincronia

![image](https://github.com/bireme/thesaurus-wp-plugin/assets/35345406/21e8cc3e-901f-40ba-8c87-a4f45e56d0e5)

O Miacci identificou o seguinte: 

[11:53] Miacci, Marco (BIR)

PHP Fatal error:  Uncaught TypeError: array_filter(): Argument #1 ($array) must be of type array, null given in /home/apps/bvsalud.org/wp-decs/htdocs/wp-content/plugins/thesaurus/template/home.php:386\nStack trace:\n#0 /home/apps/bvsalud.org/wp-decs/htdocs/wp-content/plugins/thesaurus/template/home.php(386): array_filter()\n#1 /home/apps/bvsalud.org/wp-decs/htdocs/wp-content/plugins/thesaurus/thesaurus.php(138): include('...')\n#2 /home/apps/bvsalud.org/wp-decs/htdocs/wp-includes/class-wp-hook.php(310): Thesaurus_Plugin->template_redirect()\n#3 /home/apps/bvsalud.org/wp-decs/htdocs/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()\n#4 /home/apps/bvsalud.org/wp-decs/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()\n#5 /home/apps/bvsalud.org/wp-decs/htdocs/wp-includes/template-loader.php(13): do_action()\n#6 /home/apps/bvsalud.org/wp-decs/htdocs/wp-blog-header.php(19): require_once('...')\n#7 /home/apps/bvsalud.org/wp-decs/htdocs/index.php(17): require('...')\n#8 {main}\n  thrown in /home/apps/bvsalud.org/wp-decs/htdocs/wp-content/plugins/thesaurus/template/home.php on line 386, referer: https://decs.bvsalud.org/es/ths?filter=ths_termall&q=Lesi%C3%B3n

Você poderia verificar, por favor?
Grata!

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
@wilsonmoura, Validado no ambiente de testes. Obrigada!

**Comment by wilsonmoura** [comment]
@acecampos ambiente de produção atualizado.
