### ISSUE TITLE
Criar hiperlinks para qualificadores na aba de qualificadores permitidos

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#14]
Fábio,
Uma ideia da Marilda: ao clicar na aba de qualificadores permitidos para determinado qualificador, sensibilizar cada um deles da lista para que abra em uma nova aba como popup (?) para que o usuário não tenha que refazer a pesquisa de descritor, etc.
Esta funcionalidade já era disponibilizada no site antigo.
![image](https://user-images.githubusercontent.com/35345406/67507224-e1627780-f664-11e9-8b1c-6cdbb7bbfe30.png)

**Comment by falbrito** [comment]
Realizado.
