### ISSUE TITLE
Avaliar quando não existir um resultado para a busca direcionar para outro lugar

### ISSUE THREAD

**Issue by falbrito** [bireme/thesaurus-wp-plugin#15]
Avaliar quando não existir um resultado para a busca direcionar outro lugar ao invés de mostrar "No results"

**Comment by falbrito** [comment]
Ainda, quando fazemos busca sem preencher o campo, não traz nenhum resultado (poderia trazer algo como no iahx)

**Comment by arthurtreuherz** [comment]
Uma opção é colocar a régua alfabética, talvez colocando o total de registros para cada letra. A outra opção seria que fosse sugerido ao usuário navegar pela estrutura hierárquica desde os nomes das categorias, na aba de Estrutura hierárquica que ainda está para ser criada (ver issue #52)

**Comment by wilsonmoura** [comment]
@arthurtreuherz implementamos a sugestão de exibir a árvore hierárquica quando não existir um resultado para a busca. Favor validar no ambiente de testes.

**Comment by arthurtreuherz** [comment]
Está ótimo. Só falta agora concatenar o idioma do conteúdo atual com as mensagens das duas linhas verdes claras, isto é,  a de não ter encontrado o termo "Search for: torre | No results found" e a de "DeCS/MeSH Tree View      See in another language ". Então, quando o usuário, por exemplo, busca em português essas linhas não devem estar em português. Fora isso, aprovado.

**Comment by wilsonmoura** [comment]
@arthurtreuherz traduções atualizadas.
