### ISSUE TITLE
Bug no descritor "Transsexualism" 

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#18]
Identificado um bug no idioma inglês, em que, como sinônimos, aparecem termos em espanhol da Espanha, conforme figura abaixo:
![image](https://user-images.githubusercontent.com/35345406/68028511-dbd3e580-fc93-11e9-8821-2154279b0e04.png)
Agradeço pela atenção!

**Comment by falbrito** [comment]
Realizado.
