### ISSUE TITLE
Desenvolver opção de busca exata

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/thesaurus-wp-plugin#19]

**Comment by falbrito** [comment]
Exemplo de busca utilizando **Delphinus**

Busca livre para qualquer descritor - 2 resultados
![image](https://user-images.githubusercontent.com/6940371/80370829-4347a800-8867-11ea-9079-eefc2e62b931.png)

Busca para descritor exato - 1 resultado
![image](https://user-images.githubusercontent.com/6940371/80370877-58243b80-8867-11ea-86bb-39b95a396233.png)
