### ISSUE TITLE
Permitir uso de operadores booleanos

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/thesaurus-wp-plugin#20]

**Comment by falbrito** [comment]
Qualquer descritor:

```
Pesquisado: Saúde | Resultados: 524
Pesquisado: Saude | Resultados: 524
Pesquisado: sauDE | Resultados: 524 

```
AND
```
Pesquisado: dengue and febre | Resultados: 4
Pesquisado: dengue AND febre | Resultados: 4 

```
`Pesquisado: Proteção Civil | Resultados: 3  *** Neste exemplo AND está oculto`


OR
```
Pesquisado: Batata OR Amarillo | Resultados: 36
Pesquisado: Batata or Amarillo | Resultados: 36
Pesquisado: batata or amarillo | Resultados: 36
Pesquisado: baTaTa or aMaRillo | Resultados: 36
Pesquisado: baTaTa or aMaRillo | Resultados: 36 

```
TESTE COM RADICAL
```
*
Pesquisado: den* AND feb* | Resultados: 5

```
```
* e $
Pesquisado: febre | Resultados: 86 
Pesquisado: febr$ | Resultados: 97
Pesquisado: febr* | Resultados: 97
Pesquisado: febr | Nenhum resultado foi encontrado
```

**Comment by falbrito** [comment]
Outros testes

**Qualquer descritor:**
// Search for: fisiol | No results found
// Search for: fisiol* | Results: 61
// Pesquisado: fisiol$ | Resultados: 61
// Pesquisado: $fisiol$ | Resultados: 76
// Search for: Arterivirus Aedes | No results found
// Search for: Arterivirus OR Aedes | Results: 4 
// Search for: Achyranthes calea OR Anemia Infecciosa Equina | No results found
// Search for: "Achyranthes calea" OR "Anemia Infecciosa Equina" | Results: 3
// Search for: saude | Results: 524
// Pesquisado: "Achyranthes calea" AND "Anemia Infecciosa Equina" | Nenhum resultado foi encontrado

**Descritor exato:**
// Search for: Temefos | Results: 1 
// Search for: Insecticida Abate | Results: 1
// Search for: Mosquito del Dengue | Results: 1 
// Search for: Mosquito-da-Febre-Amarela | Results: 1 

**ID:**
// Pesquisado: D000005 | Resultados: 1 

**Qualquer qualificador:**
// Search for: fisiol | No results found 
// Search for: fisiol* | Results: 1
// Search for: fisiol$ | Results: 1
// Search for: $fisiol$ | Results: 2 
// Search for: \*fisiol\* | Results: 2
// Search for: *fisiol$ | Results: 2 

// Search for: efectos adversos OR líquido cefalorraquídeo | No results found 
// Search for: "efectos adversos" OR "líquido cefalorraquídeo" | Results: 2 
// Search for: "administración & dosificación" OR "líquido cefalorraquídeo" | Results: 2 

// Search for: efectos adversos AND líquido cefalorraquídeo | No results found 
// Search for: "efectos adversos" AND "líquido cefalorraquídeo" | No results found 
// Search for: "administración & dosificación" AND "líquido cefalorraquídeo" | No results found
