### ISSUE TITLE
Busca permutada em Qualificadores

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#23]
Fábio,
Conforme conversado remotamente, a pesquisa permutada em **qualificadores** tem tido resultado Zero:

![image](https://user-images.githubusercontent.com/35345406/77322872-29a8c300-6cf3-11ea-8351-ff09cf95e9e6.png)

![image](https://user-images.githubusercontent.com/35345406/77322256-3973d780-6cf2-11ea-8b71-33b8d7c2f9ed.png)

Grata!

**Comment by acecampos** [comment]
Fabinho, para descritores também não está funcionando se escrevermos só parte da palavra.

**Comment by falbrito** [comment]
@acecampos 
Deve-se colocar o wildcard * para poder buscar pelo radical
ex.: fisio*

![image](https://user-images.githubusercontent.com/6940371/83146025-0ec84580-a0cc-11ea-82a7-a2bf6d9f8ebc.png)
