### ISSUE TITLE
Sempre mostrar a aba Qualificadores (para os qualificadores permitidos) nos registros de descritores no sistema público de consulta e no sistema de gestão permitir a edição para registros exclusivos

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#41]
Esse é um melhoramento, pra ficar igual ao sistema da NLM:  

Na NLM, quando o descritor tem "qualificador permitido" (ou seja, quando é permitido coordenar o descritor com um ou mais qualificadores) e também quando o descritor não tem qualificadores permitidos, o sistema mostra a aba "Qualificadores". Na verdade trata-se dos "Qualificadores permitidos" ou "Allowed qualifiers", só que eles apenas chamam essa aba de "Qualifiers", o que fica um pouco ambíguo. Veja, por exemplo, o descritor Water Microbiology/Microbiologia da Água no MeSH e no DeCS:

- Water Microbiology : https://meshb.nlm.nih.gov/record/ui?ui=D014871
- Microbiologia da Água : https://decs.bvsalud.org/ths/resource/?id=15275&filter=ths_termall&q=microbiologia%20da%20agua

Agora veja esse outro exemplo, Physical Phenomena, de quando o descritor não tem qualificador permitido. O sistema da NLM também mostram a aba e escreve "No Qualifiers".  

- Physical Phenomena : https://meshb.nlm.nih.gov/record/ui?ui=D055585
- Fenômenos Físicos : https://decs.bvsalud.org/ths/resource/?id=53273&filter=ths_termall&q=fenomenos%20fisicos

No nosso sistema atual de consulta não existe essa aba de "qualificadores permitidos". O que existe é o campo "Qualificadores permitidos" entre os outros campos mostrados, que é o mesmo formato que já existia na versão anterior do MeSH Browser e DeCS de consulta.

Você poderia alterar o formato de apresentação para, que mesmo que o descritor não tenha "qualificadores permitidos", o sistema público de consulta mostra esse campo, preenchendo o conteúdo com "Sem qualificador" no português, "Sin calificador" no espanhol, "No qualifiers" no inglês e "Aucun qualificatif".

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados conforme solicitado. Favor validar no ambiente de testes do Portal DeCS.

**Comment by acecampos** [comment]
@wilsonmoura perfeito! 
![image](https://user-images.githubusercontent.com/35345406/210096995-1047fbec-5796-4788-9c3e-411708627638.png)

@lucianaPRB e eu agradecemos!
