### ISSUE TITLE
Ao fazer pequisa por termo exato, direcionar para registro inteiro

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#47]
Fábio, 
A fim de evitar um click a mais, sugiro que, ao fazer a pesquisa por termo exato, o resultado da pesquisa seja diretamente o registro onde o termo aparece. Assim, pode-se ter acesso ao código hierárquico do registro e às notas de indexação e de escopo com um passo a menos.

![image](https://user-images.githubusercontent.com/35345406/83771210-6df00200-a658-11ea-9ef7-5d18cb109852.png)

Obrigada!

**Comment by falbrito** [comment]
Realizado.
