### ISSUE TITLE
Bug no código hierárquico

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#49]
Fábio, bom dia! Ao fazer uma pesquisa para enumerar (e quantificar) descritores na categoria SH e entrei a pesquisa por "Código hierárquico" com sh*. O primeiro resultado que apareceu parece ser um bug. Apareceu "without translation":
![image](https://user-images.githubusercontent.com/35345406/84738018-80830900-af7f-11ea-819c-de68b6b1b903.png)

**Comment by falbrito** [comment]
Correção realizada.
