### ISSUE TITLE
Desenvolver o módulo de navegação na árvore hierárquica do DeCS a partir do nível zero ou de nomes de categorias

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#52]
O módulo deve ser semelhante ao que existe no site do MeSH, isto é, incluir no Menu, o item "Visão Hierárquica", "Visión Jerárquica", "Tree View", "Vue arborescente".

![image](https://user-images.githubusercontent.com/25855735/85896222-78706800-b7ce-11ea-9d02-3b6fe946c907.png)

Clicando-se em Tree View, abre-se a página onde são mostrados os nomes das categorias do MeSH:

![image](https://user-images.githubusercontent.com/25855735/85896439-d735e180-b7ce-11ea-9ab5-7965ec6bb4e1.png)

**Comment by wilsonmoura** [comment]
@arthurtreuherz árvore hierárquica implementada. Favor validar.

Link para visualização: https://decs.teste.bvs.br/ths/treeView

**Comment by arthurtreuherz** [comment]
Muito legal! Parabéns! Acho que só precisaria agora incluir o link "Visão Hierárquica" entre a palavra "Início" e "Sobre o DeCS" no menu horizontal "Início | Sobre o DeCS | Edição atual | Edições anteriores | Serviços web | Fale conosco.

Links para os outros idomas:

Visión Jerárquica
Tree View
Vue Hiérarchique

**Comment by arthurtreuherz** [comment]
Na verdade está muito grande, então não está mostrando os que possuem níveis acima de uns oito níveis. E já existem 13 níveis.

Veja a diferença quando você pesquisa "Macaca mulatta" por termo exato 

![image](https://user-images.githubusercontent.com/25855735/115903785-608f6200-a43a-11eb-8c68-ca1266935265.png)

e mostra a visão hierárquica versus quando você navega pelo seu novo módulo de navegação hierárquica até chegar lá.

![image](https://user-images.githubusercontent.com/25855735/115904140-d267ab80-a43a-11eb-9581-4783011963df.png)

Tem que diminuir o tamanho da letra (ou desde o início ou conforme vai indo para níveis mais altos)
Outra saída seria mover tudo para a esquerda.

**Comment by wilsonmoura** [comment]
@arthurtreuherz ajustes realizados. Favor validar.

**Comment by arthurtreuherz** [comment]
Muito bom. Aprovado. Obrigado. Agora só percebo que precisa inserir no menu, conforme mencionado acima.

**Comment by wilsonmoura** [comment]
@arthurtreuherz link incluído no menu conforme solicitado. Favor validar.
@acecampos implementado menu para alterar idioma. Favor validar.

![screenshot-decs teste bvs br-2021 04 23-18_19_15](https://user-images.githubusercontent.com/3779520/115930983-c4c51c80-a460-11eb-87f6-42ad4e47a70a.png)

**Comment by arthurtreuherz** [comment]
Excelente Wilson. De minha parte super aprovado! Você é o cara! bom fim de semana.

**Comment by acecampos** [comment]
Validada a implementação do menu para alterar o idioma! Muito boa a ideia de colocar "Veja em outro idioma".
