### ISSUE TITLE
Verificar porque o termo SARS-CoV-2 não traz resultado

### ISSUE THREAD

**Issue by falbrito** [bireme/thesaurus-wp-plugin#59]
No caso, se for colocado o termo SARS-CoV-2 entre aspas funciona.

**Comment by renatomurasaki** [comment]
Verificar as novas regras de tokenização que foram desenvolvidas para BVS Regional e WHO COVID-19

**Comment by wilsonmoura** [comment]
@arthurtreuherz ajustes realizados. Favor validar.

**Comment by arthurtreuherz** [comment]
Obrigado Wilson. Melhorou muito. Agora **acha** quando é "Descritor Exato" e **também acha** quando é "Qualquer termo". Só que o sistema agora acha termos COM HÍFEN só quando se busca com a "caixa" idêntica a como está na base. Precisaria também encontrar quando o usuário escreve tudo em minúsculo ou tudo em maiúsculo ou de qq jeito, sem importar a "caixa". Senão vão chiar. Se você busca por sars-cov-2 ainda não encontra. Dá pra melhorar isso também?

**Comment by wilsonmoura** [comment]
@arthurtreuherz ajustes realizados com apoio do @viniciusandrade. Favor validar novamente.

Commit: https://github.com/bireme/fi-admin-idx/commit/1bf18d228f272b65d725b4bf75e2d46e03c10dde

**Comment by arthurtreuherz** [comment]
Excelente! Obrigado e, por mim, validado.
