### ISSUE TITLE
Planejar o desenvolvimento da nova plataforma de web services

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/thesaurus-wp-plugin#63]
Importante manter compatibilidade com a assinatura e resposta do serviço legado

**Comment by wilsonmoura** [comment]
@renatomurasaki web service implementado em https://github.com/bireme/fi-admin/pull/1227. Adicionado parâmetro `tree_id`. Falta ainda incluir os parâmetros `words` e `bool`.

Exemplos de chamadas de:
- Descritor: https://fi-admin.teste.bvsalud.org/api/ths/tree_number/?tree_id=D03.633.100.221
- Qualificador: https://fi-admin.teste.bvsalud.org/api/ths/tree_number/?tree_id=Q15

**Comment by wilsonmoura** [comment]
Esse web service será implementado em um repositório dedicado: https://github.com/bireme/decs-api
