### ISSUE TITLE
Criar links na visualização dos termos para recuperar documentos na BVS

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/thesaurus-wp-plugin#65]

**Comment by arthurtreuherz** [comment]
Vide campo "Ocorrência na BVS" nesse exemplo do descritor Pobreza no sistema antigo. Esse serviço de interoperabilidade entre o vocabulário DeCS e as bases bibliográficas deveria ser implementado com certa urgência na consulta atual.

http://decs2020.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&task=exact_term&show_tree_number=T&previous_page=homepage&interface_language=p&search_language=p&search_exp=Pobreza&umls=all

**Comment by wilsonmoura** [comment]
@arthurtreuherz @renatomurasaki realizei ajustes no ambiente de testes. Favor validar. Segue link e imagem com exemplo:

https://decs.teste.bvs.br/ths/resource/?id=31543&filter=ths_termall&q=covid

![screenshot-decs teste bvs br-2021 04 16-15_11_05](https://user-images.githubusercontent.com/3779520/115066550-10f2e880-9ec6-11eb-88e3-ca01e263b2e4.png)

**Comment by renatomurasaki** [comment]
@arthurtreuherz e @wilsonmoura no momento de gerar o link para a BVS, coloque mh:("nome do descritor") ao invés do código hierárquico.

**Comment by arthurtreuherz** [comment]
Renato, aproveitando o seu pedido de colocar o nome do descritor, e se implementasse : com explosão e sem explosão? Sem explosão mostra apenas o descritor, com explosão pesquisa o código com cifrão e mostra, mas também mostra o nome (ou então só mostra o código se quiser explosão?).

Sobre a o novo nome do campo e simplificação pra a BVS inteira, pro Wilson poder mexer, Renato, que tal esse novo texto para o nome atualizado nos 4 idiomas?

português: Documentos indexados na Biblioteca Virtual em Saúde (BVS)
espanhol: Documentos indizados en la Biblioteca Virtual de Salud (BVS)
inglês: Documents indexed in the Virtual Health Library (VHL)
francês: Documents indexés dans la Biblioteque Virtuelle de Santé (BVS)

**Comment by wilsonmoura** [comment]
@arthurtreuherz @renatomurasaki realizei ajustes no ambiente de testes. Favor validar. Segue link e imagem com exemplo:

https://decs.teste.bvs.br/ths/resource/?id=31543&filter=ths_termall&q=covid

![screenshot-decs teste bvs br-2021 04 16-19_29_27](https://user-images.githubusercontent.com/3779520/115090025-1f52fb80-9eea-11eb-9931-116c95e96732.png)

**Comment by arthurtreuherz** [comment]
@wilsonmoura e @renatomurasaki, por mim está ótimo, só faltaria traduzir os nomes dos campos (conforme acima) e o texto à direita com o hyperlink. Traduzindo ao pé da letra esse que você propõe:

Haga clic aquí para acceder a los documentos de la BVS
Clique aqui para acessar os documentos da BVS
Cliquez ici pour accéder aux documents VHL

**Comment by arthurtreuherz** [comment]
Wilson, hoje procurei um issue que eu tinha feito pro Fábio pra inclusão de outros campos (esse acima era um deles) que ainda estão pendentes de aparecerem no sistema de consulta (Portal) e que já aparecem no FI-ADMIN. Você de qual eu estou falando? Só que não encontrei. 

O que encontrei foi uns e-mails de agosto de 2020 trocados com o Fábio pra produção da versão atualizada e completa do XML bilíngue do DeCS, quando ele incluiu alguns campos que faltavam no XML e no FI-ADMIN, provenientes do do XML do MeSH. Alguns desses campos só faltam agora mostrar no sistema de consulta. Preciso criar um issue separado pra pedir isso?

Para entender o que digo, aqui vão alguns exemplos de descritores que contêm esses campos. Você consegue encontrá-los hoje no XML e no MeSH Browser: https://meshb.nlm.nih.gov

1. Primeiro registro da base, de química, **Calcimycin**. Contém campos como 

 RDF Unique Identifier, 
 Pharmacological Action" e "Pharmacological Action List, 
 Registry Number, 
 Related Numbers, 
 CAS Type 1 Name, 
 Previous Indexing, 
 History Note, 
 Online Note, 
 Public MeSH Note.   

 DescriptorUI = D000001

1. Registro **Anesthesia**. Contém o campo **EntryCombinationList**, ou seja, contém mais de um EntryCombination.  DescriptorUI = D000758

3. Registro **Neoplasms**. Contém os campos pendentes 

 Annotation
 ConsiderAlso
 Entry Combination
 Entry Version
 History Note
 Public MeSH Note
 
 DescriptorUI = D009369

4. Registro **Bone and Bones**. Contém quase todos os campos como, por exemplo, esses pendentes no nosso portal:

 Annotation
 Consider Also
 Entry Combination
 Entry Version
 History Note
 Online Note
 Public MeSH Note

 DescriptorUI = D001842

**Comment by wilsonmoura** [comment]
@arthurtreuherz realizei ajustes para exibir os campos mencionados. Favor validar.

**OBS 1:** Em todos os testes, o campo **Related Numbers** foi o único campo que não constou nos metadados recuperados dos descritores.

**OBS 2:** Em alguns casos, existem campos que só possuem conteúdo em um idioma específico. Sendo assim, recomendo escolher o idioma inglês ao realizar os testes de visualização dos campos e assim garantir a exibição dos metadados mencionados.

**Comment by arthurtreuherz** [comment]
Perfeito! Tem toda razão quanto à observação 2. Se puder implementar essa sugestão será ótimo também. Muito obrigado.
Poderia também alterar a ordem de apresentação do campo "ID do descritor"/"Descriptor UI"/ "ID del Descriptor" / "ID du Descripteur", para que apareça logo abaixo dos códigos hierárquicos, como faz a NLM?

**Comment by wilsonmoura** [comment]
@arthurtreuherz na verdade, a observação 2 era apenas uma orientação no momento de validar a exibição dos novos campos. Mas se for o caso, eu posso seguir com a sua sugestão.

**Comment by arthurtreuherz** [comment]
Sim, validado. E se puder, pode seguir com a minha sugestão. Obrigado.

**Comment by arthurtreuherz** [comment]
Wilson, por favor, coloque uma condição para o campo 

RDF Unique Identifier

Caso o registro não for do MeSH, isto é, caso o registro possua o DescriptorUI começando com DDCS então não mostrar esse campo. Senão o usuário curioso vai clicar e não vai achar o registro na NLM. Obrigado.
