### ISSUE TITLE
Na geração do DeCS do Portal, caso o descritor em inglês não tiver uma ScopeNote, mover a ScopeNote do PEP de ConceptUI mais próximo para o ScopeNote do conceito preferido desse descritor

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#66]
Hoje encontrei um descritor novo do MeSH cujo descritor (Sanitary Surveys, Water Supply) estava sem definição na planilha produzida em outubro de 2020 pela NLM para tradução. Mas esse descritor tem um PEP (conceito não preferido) e esse tem uma definição. Aí, eu vi que no MeSH browser essa definição está no conceito preferido, isto é no descritor e não no PEP (ou seja, de duas uma: ou a NLM tem um procedimento que identifica se o descritor está sem definição move a do seu primeiro PEP para ele, apenas no Browser, ou eles atualizaram o registro, alterando fisicamente a nota para o conceito preferido.)

Apesar ser um erro conceitual (pois o conteúdo dessa definição cobre o significado do PEP e não do descritor, ligeiramente mais específico), para nós é bom, pois assim no nosso sistema de consulta a definição vai aparecer. Senão o usuário só enxergaria a definição se abrisse o conceito. Geralmente os descritores do MeSH possuem definição, mas quando não possuem, geralmente apenas um de seus PEPs possuem definição.

Por isso, para resolver para os outros casos em que isso acontece, quando for possível, solicito que para o DeCS do portal de consulta no WP, "se o MH não tiver definição, mas algum de seus PEPs tiverem, mostrar a do primeiro PEP por ordem numérica de ConceptUI do descritor. Obrigado.

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura, eu não concordo com essa proposta do Arthur. @lucianaPRB, por favor, emita um parecer sobre esse issue.

**Comment by lucianaPRB** [comment]
@acecampos e @wilsonmoura Eu também não concordo com essa proposta. Acredito que este issue pode ser encerrado sem prejuízo
