### ISSUE TITLE
Mostrar o PEP em inglês para o usuário quando este ainda não tiver uma tradução para o idioma do conteúdo desejado

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#67]
Esse issue é parecido com o #66 só que para PEP, ao invés de nota de escopo.

Favor mostrar para o usuário o PEP em inglês quando este não tiver uma tradução noutro idioma. Existem muitos PEPs que ainda estão sem tradução. Assim, o usuário saberá quantos conceitos não preferidos existem.

Da mesma forma, este PEP estiver traduzido somente em um espanhol e ele estiver na interface do outro espanhol, mostrar essa tradução ao invés de mostrar o inglês ou de não mostrar nada.

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura não concordo com essa proposta do Arthur. @lucianaPRB, por favor, emita seu parecer técnico sobre esse issue.

**Comment by lucianaPRB** [comment]
Acredito que esse issue não é necessário.
