### ISSUE TITLE
Ajustar para mostrar todos os sinônimos de cada idioma também na visão no primeiro resultado antes de clicar no botão "Veja detalhes". Hoje só mostra alguns sinônimos.

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#69]
Abaixo mostro dois exemplos em que o problema aparece. Ao final, creio que encontrei o motivo. Favor ajustar, obrigado.

Ao pesquisar na versão em inglês com o índice "Any term" por **Freckles**, o sistema recupera corretamente dois registros. Mas no resultado apenas é possível ver a palavra "Freckles" em um dos registros. Parece que para o inglês, em vez do sistema mostrar o termo contendo a palavra ele o está ocultando. 

![image](https://user-images.githubusercontent.com/25855735/116405210-c480a480-a805-11eb-940e-cf0183b3134a.png)

Quando abrimos para ver os detalhes percebemos que o registro possui mais sinônimos e só então é possível ver o segundo termo que possui a palavra "Freckles" no plural.

![image](https://user-images.githubusercontent.com/25855735/116405446-090c4000-a806-11eb-91b7-87928c887b56.png)

Você poderá confirmar esse problema também nesse outro exemplo, pesquisando na versão em inglês em "Any term" pela palavra **whales**. Você verá que no registro 4 de um total de 10 registros muitos sinônimos são mostrados. Mas aqueles 3 termos contendo a palavra "whales" no plural não estão sendo mostrados no primeiro resultado (antes de clicar em "See details".

Suspeito que o sistema está configurado para ocultar na primeira tela os termos nos quais o parâmetro PermuttedTermYN="Y". Se for isso, a solução é retirar essa condição do procedimento, permitindo que esses termos também possam aparecer. No exemplo do Whales, outros termos que possuem Y no PermuttedTermYN também não apareceram no primeiro resultado.

**Comment by wilsonmoura** [comment]
@arthurtreuherz ajustes realizados. Favor validar.

**Comment by arthurtreuherz** [comment]
Validado. Obrigado Wilson. Boa noite.
