### ISSUE TITLE
Verificar pesquisa com termos que possuem diacrítico mas não retornam resultado

### ISSUE THREAD

**Issue by falbrito** [bireme/thesaurus-wp-plugin#7]
Verificar pesquisa com termos que possuem diacrítico mas não retornam resultado.

Testes realizados com termos com diacríticos

**Testes que foram bem - OK**
Dengue sévère
((4-(1,4,5,6-tetrahidro-4-metil-6-oxo-3-piridazinil)fenil)hidrazono)propanodinitrilo
A 127722
(2R)-(1R)-3,5-bis(trifluorometilfenil)etoxi)-(3S)-(4-fluoro)fenil-4-(3-(5-oxo-1H,4H-1,2,4-triazol)metil-morfolina
Aprépitant

**Teste que deveriam funcionar - NOK**
Fièvre jaune  <-- não passou
Virus de la fièvre jaune <-- não passou

**Comment by arthurtreuherz** [comment]
Favor verificar os seguintes acentos cujas linhas terminam com ERRO.

Teste com **análise** (a agudo minúsculo) recupera 129 linhas (descritores) - OK
Teste com **Árvores** (A agudo maiúsculo) OK

Teste com **Tarântula** (a circunflexo minúsculo) OK
Teste com **Âgisme** (em francês) e **Ânsia** (em português) (a maiúsculo com acento circunflexo) OK

Teste com **Anão** (a com til minúsculo). Encontra termos que não possuem hífen. **Não encontra aqueles com hífen**:
Exemplos: 

Termos encontrados:

- Anão Hipofisário      OK
- Cachalote Anão      OK
- Macaco Lêmure Anão      OK

Termos não encontrados:

- Hamster-Anão-Russo-Siberiano        Não encontrado. ERRO
- Zimbro-Anão         Não encontrado. ERRO
- Cravo-Anão           Não encontrado. ERRO

Teste com **Santé** em francês e **Género** em espanhol (e agudo minúsculo). Não recuperam nada. ERRO
Teste com **Ésteres** (e agudo maiúsculo) Não recupera nada. ERRO

Teste com **Gênero** (e circunflexo minúsculo). Não recupera nada. ERRO
Teste com ** Êxito** (E circunflexo maiúsculo). Não recupera nada. ERRO.

Teste com **Início** (i agudo minúsculo) recupera 15 pelo **novo** sistema e 17 registros pelo **antigo** (motivo: o sistema antigo só procurou quem tem **inicio** no termo em português. Há outros 2 termos em espanhol. O sistema novo busca em todos os idiomas, então trouxe resultado pois há **inicio** sem acento.) (não encontrou o termos com início acentuado como "Ataxia Cerebelar de Início Precoce" e "Ataxia Cerebelar de Início Tardio") ERRO
Teste com **Índio** (I agudo maiúsculo) OK

Teste com **Códon** (acento o agudo minúsculo) OK
Teste com **Óculos** (acento O agudo maiúsculo). Não trouxe nada. ERRO.

Teste com **Insônia** (acento o circunflexo minúsculo). Não trouxe nada. ERRO
Teste com **Ômega** (acento O circunflexo maiúsculo). Não trouxe nada. ERRO

Teste com ** Fusões** (o minúsculo com til). Há 91 termos com Lesiones e zero com Lesões. Na base congelada de 2019 na homologação há 141 descritores com Lesões. ERRO.

G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if v3:'ões' and not v3:'ções' then mfn/ fi" now lw=0 | wc
    141     141     987

Teste com **Saúde** (u agudo). Só recupera um resultado. ERRO
Teste com ** Único** e ** Única**. Não recupera nada. ERRO

Teste com **Criança** e ** Doença** (c cedilha minúsculo). Não recupera nada. ERRO
Teste com **CRIANÇA** e ** DOENÇA** (c cedilha maiúsculo). Não recupera nada. ERRO

Teste com **Sueño** (n com til). Não recupera nada. ERRO
Teste com **Frijol de Ñame** (N com til). Não recupera nada. ERRO.

Teste com ** Schüssler** (u com trema minúsculo). Não recupera nada. ERRO (deveria trazer 2 descritores em português ("Sais de Schüssler" e "Hormônio Antimülleriano"), 11 descritores em espanhol latinoamericano,  9 descritores da Espanha, 19 sinônimos em português, 45 sinônimos em espanhol latinoamericano, 27 sinônimos em espanhol da Espanha, 212 sinônimos em francês. (números da homologação com mx)

Teste com **Sjögren** (o com trema minúsculo). OK

O sistema deve substituir a letra com o acento pela letra sem o acento (tirar o acento), fazer a busca e aí então mostrar o resultado com o acento (ou buscar tanto quem tem quanto quem não tem o acento). Por exemplo: a palavra inicio existe em espanhol e em português, mas só tem acento em português. Então deve recuperar tanto os termos em espanhol quanto em português.

Grato,
Arthur

**Comment by falbrito** [comment]
Revendo problemas 

```
Teste com ** Fusões** (o minúsculo com til). Há 91 termos com Lesiones e zero com Lesões. Na base congelada de 2019 na homologação há 141 descritores com Lesões. ERRO.

G4 serverw:/home/decs2019/www/bases $ mx decs "pft=if v3:'ões' and not v3:'ções' then mfn/ fi" now lw=0 | wc
141 141 987

```

e 

`Teste com ** Schüssler** (u com trema minúsculo). Não recupera nada. ERRO (deveria trazer 2 descritores em português ("Sais de Schüssler" e "Hormônio Antimülleriano"), 11 descritores em espanhol latinoamericano, 9 descritores da Espanha, 19 sinônimos em português, 45 sinônimos em espanhol latinoamericano, 27 sinônimos em espanhol da Espanha, 212 sinônimos em francês. (números da homologação com mx)
`

todos os demais trouxeram resultados
