### ISSUE TITLE
Na instância teste, ajustar a mudanças de idioma

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#70]
Na instância de testes, https://decs.teste.bvs.br, quando o usuário muda o idioma em cima do logo da Bireme (chamemos de idioma da interface) (o default é o português), o texto da linha com as abas "Detalhes | Estruturas Hierárquicas | Conceitos|  Veja em outro idioma" também muda. Hoje parece que esse texto dessa linha está cravado no inglês: "Details | Tree Structures | Concepts|  See in another language". Ele deve mudar para o novo idioma da interface solicitada também. Já o conteúdo do registro, os dados, estão mudando corretamente quando o usuário pede para mudar no "Veja em outro idioma/See in another language").

Mas a linha "Visão selecionada em Espanhol" ou "Visão selecionada em Português" etc. também deve aparecer quando o usuário pede para mudar o conteúdo do conteúdo (dos dados) quando ele clica no link "Veja em outro idioma", mas o texto desta linha permanece no idioma da interface.

Na instância pública, https://decs.bvsalud.org, ambas as ações acima estão corretas.

**Comment by wilsonmoura** [comment]
@arthurtreuherz Realizei testes e parece que está funcionando corretamente. Pode dar mais exemplos? Aproveito pra informar que atualizei o mecanismo de tradução e todos os textos estão atualizados no ambiente de testes. Por favor, peço que realize mais testes. Caso o problema ainda ocorra, talvez possamos fazer uma reunião para alinhar o que deve ser feito.

**Comment by arthurtreuherz** [comment]
Agora ficou bom. Você mexeu no procedimento? Se não mexeu é muito estranho que ontem isso tenha acontecido para mim. Mas hoje está ótimo. Vi que quando o o usuário clica no idioma do topo da página (interface) não só o idioma da interface como o do conteúdo mudam. No sistema antigo havia duas formas de alterar o idioma da interface: uma era na homepage nos links do canto superior direito. 

Nessa primeira forma, o idioma do conteúdo também alterava junto. 

![image](https://user-images.githubusercontent.com/25855735/116555326-a16ff680-a8d2-11eb-89ed-9b3c08ad630f.png)

A segunda forma era através do botão config. Nessa página o usuário podia alterar o idioma da interface mas o do conteúdo ainda ficava setado como estava antes. 

![image](https://user-images.githubusercontent.com/25855735/116555688-0c213200-a8d3-11eb-8e84-b87ed1bee2c6.png)

http://decs2020.bvsalud.org/cgi-bin/wxis1660.exe/decsserver/?IsisScript=../cgi-bin/decsserver/decsserver.xis&interface_language=p&previous_page=homepage&previous_task=NULL&task=start

![image](https://user-images.githubusercontent.com/25855735/116555115-5d7cf180-a8d2-11eb-9b13-0f0be8e324d0.png)

Mas acho que isso está bem, pois se o usuário quer mudar o idioma da interface é quase certo (acho que na grande maioria das vezes) que ele também vai querer ver o conteúdo do registro nesse novo idioma. Assim, o sistema fica um pouquinho mais simples. Obrigado.

**Comment by arthurtreuherz** [comment]
Sobre o que você disse

"atualizei o mecanismo de tradução e todos os textos estão atualizados no ambiente de testes. Por favor, peço que realize mais testes. Caso o problema ainda ocorra, talvez possamos fazer uma reunião para alinhar o que deve ser feito."

realizei teste a respeito de idioma das notas. Quando em um idioma de conteúdo não existir notas, favor mostrar o seguinte:

Quando existir **nota de escopo** em algum idioma, mas não existir nota de escopo no 

- inglês, mostrar em português. Se também não tiver no português, mostrar no espanhol da Espanha. Se também não tiver em espanhol da Espanha, mostrar no espanhol regional.

- espanhol regional, mostrar em espanhol da Espanha. Se também não tiver em espanhol da Espanha, mostrar em inglês. Se também não tiver em inglês, mostrar em português.

- português, mostrar em inglês. Se também não tiver em inglês, mostrar em espanhol da Espanha. Se também não tiver em espanhol da Espanha, mostrar no espanhol regional.

- francês, mostrar em inglês.

**Comment by arthurtreuherz** [comment]
Em relação à nota de indexação (Annotation), a lógica muda um pouquinho, sendo um pouco mais simples, pois não há nota em espanhol da Espanha:

Então quando existir **nota de indexação (Annotation)** em algum idioma mas não existir essa nota em

- inglês, mostrar em português. Se também não tiver no português, mostrar no espanhol regional.

- espanhol regional, mostrar em inglês. Se também não tiver em inglês, mostrar em português.

- português, mostrar em inglês. Se também não tiver em inglês, mostrar no espanhol regional.

- francês, mostrar em inglês.

**Comment by wilsonmoura** [comment]
@arthurtreuherz não sei se isso é o ideal, pois seguindo a lógica da sua sugestão, o mesmo registro pode exibir campos em vários idiomas diferentes. Além também de gerar mais processamento para exibição das informações sobre aquele registro. Na grande maioria dos sistemas, é exibido um idioma padrão (normalmente no idioma inglês) quando não se encontra conteúdo no idioma de navegação. Se mesmo assim isso for realmente necessário, eu posso seguir com a sua sugestão.

**Comment by arthurtreuherz** [comment]
ok. obrigado. validado.
