### ISSUE TITLE
Diminuir tamanho da letra da aba Conceitos em todos os idiomas na instância teste conforme a instância pública

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#71]
Apenas na aba **Conceitos** da **instância teste**, o tamanho da letra está muito grande. Na instância pública está ok. Isso complica a visualização na hora de expandir os hyperlinks de cada conceito, pois os registros muitas vezes são bem grandes. Por isso, assim como foi feito para a aba Estruturas Hierárquicas, peço que se diminua o tamanho da letra para o tamanho que está na instância pública. Exemplo: Dolphins.

**Comment by arthurtreuherz** [comment]
Não sei se você já acertou (se foi, obrigado), ou se foi algum problema com o meu laptop, mas creio que ficou bom, portanto, não precisaria fazer mais nada. Mas se você mexeu no tamanho, se o Renato concordar, peço que diminua ou pouco mais, para que fique mais parecido com o tamanho da instância do MeSH. Parece que eles usam tamanho 10,5. O que você acha?

**Comment by wilsonmoura** [comment]
@arthurtreuherz eu não fiz nenhum ajuste. Provavelmente foi o cache no seu browser. Posso então desconsiderar esse issue?

**Comment by arthurtreuherz** [comment]
Entendo que realmente o problema maior estava provavelmente no meu browser. Mesmo assim, o tamanho da letra na aba Conceitos ainda está bem maior do que nas outras abas e bem maior do que no MeSH. Por favor, compare esse exemplo nos 3 browsers na aba Concepts.

https://meshb.nlm.nih.gov/record/ui?ui=D004289

https://decs.teste.bvs.br/en/ths/resource/?id=4349&filter=ths_regid&q=D004289

https://decs.bvsalud.org/en/ths/resource/?id=4349&filter=ths_regid&q=D004289

Você poderia diminuir um pouco mais o tamanho da letra dessa aba?

**Comment by wilsonmoura** [comment]
@arthurtreuherz ajustes realizados. Favor validar.

**Comment by arthurtreuherz** [comment]
O tamanho da letra da visualização inicial da aba "Conceitos" ficou ótima. Obrigado. Agora só falta diminuir também o tamanho da letra do conteúdo de cada conceito, que o usuário visualiza ao clicar no nome (com hipertexto) de cada conceito. Repare a diferença entre o nosso sistema e o do MeSH para o descritor Neoplasias (Neoplasms). No deles o registro inteiro coube.

https://decs.teste.bvs.br/ths/resource/?id=9562&filter=ths_exact_term&q=cancer#Concepts

![image](https://user-images.githubusercontent.com/25855735/116632071-a6fa2a80-a92c-11eb-9398-a35bfbb1b4d8.png)

https://meshb.nlm.nih.gov/record/ui?ui=D009369

![image](https://user-images.githubusercontent.com/25855735/116631971-6c908d80-a92c-11eb-8fea-5748cb74fd2d.png)

**Comment by wilsonmoura** [comment]
@arthurtreuherz veja um print da minha tela. Aqui aparecem nos tamanhos corretos. Creio que ainda esteja relacionado com o cache do seu browser. Por favor, tente limpar o cache novamente. Caso o problema persista, seria bom verificarmos se isso também ocorre com outros usuários, pois pode ser algo específico com a resolução do seu monitor.

![screenshot-decs teste bvs br-2021 04 30-11_02_40](https://user-images.githubusercontent.com/3779520/116706251-d1d39580-a9a3-11eb-88d0-6a7d30c639af.png)

**Comment by arthurtreuherz** [comment]
Acho que não tem a ver com cache, mas tudo bem, acho que o conteúdo ao clicar sobre o conceito ainda está um pouco grande (talvez também seja o espaço entre parágrafos e entre linhas). Mas não isso não é tão prioritário. Obrigado. Validado.
