### ISSUE TITLE
Inclusão dos htmls dos descritores novos

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#72]
Para registro também aqui no github, fizemos reunião hoje Márcio, Ana e eu. O Márcio nos apoio para

- mover a página atual anterior (de 2020) para "Edições anteriores", 

- criação da página "Edição atual" no WP, e 

- carregar nela os 3 arquivos html fornecidos por mim depois de convertido pelo Wilson ao formato mais adequado para o WP.

Realizamos essas ações para os quatro idiomas, copiando o inglês também na interface em francês, devido ao INSERM ainda não ter iniciado a colaboração.

Do resultado alcançado, falta apenas identificar porque em dois idiomas os links criados só abrem com ctrl-click. Márcio vai investigar até segunda-feira, quando nos reuniremos novamente para o carregamento dos htmls dos descritores alterados, que serão entregues até lá. 

https://decs.teste.bvs.br/en/decs-2021-new-descriptors/
https://decs.teste.bvs.br/es/descriptores-nuevos-2021/
https://decs.teste.bvs.br/descritores-novos-2021/
https://decs.teste.bvs.br/fr/decs-2021-new-descriptors/   ==>   https://decs.teste.bvs.br/en/decs-2021-new-descriptors/

**Comment by wilsonmoura** [comment]
@arthurtreuherz esse problema estava ocorrendo durante os testes de segurança que estavam sendo realizados no servidor. O Marcio comentou comigo sobre esse detalhe e já resolvemos isso.

**Comment by arthurtreuherz** [comment]
Certo. Ele me mostrou depois que já está ok. Obrigado.
