### ISSUE TITLE
Mensagem de erro ao pesquisar na interface em português com o íncide o termo Maus-tratos ao idoso

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#73]
Ao pesquisar o termo **maus-tratos ao idoso** na interface em português da instância de teste (creio que com o índice "Qualquer termo", o sistema me deu a segunte mensagem:

Array
(
    [0] => Array
        (
            [term_string] => Abuse, Aged
            [language_code] => en

        )

    [1] => Array
        (
            [term_string] => Abuse, Elder
            [language_code] => en

        )

    [2] => Array
        (
            [term_string] => Aged Abuse
            [language_code] => en

        )

    [3] => Array
        (
            [term_string] => Elder Neglect
            [language_code] => en

        )

    [4] => Array
        (
            [term_string] => Neglect, Elder
            [language_code] => en

        )

    [5] => Array
        (
            [term_string] => abandono de ancianos
            [language_code] => es-es

        )

    [6] => Array
        (
            [term_string] => maltrato de ancianos
            [language_code] => es-es

        )

    [7] => Array
        (
            [term_string] => negligencia de mayores
            [language_code] => es-es

        )

    [8] => Array
        (
            [term_string] => Descuido del Anciano
            [language_code] => es

        )

    [9] => Array
        (
            [term_string] => Maltrato del Viejo
            [language_code] => es

        )

    [10] => Array
        (
            [term_string] => Mauvais traitements des personne âgées
            [language_code] => fr

        )

    [11] => Array
        (
            [term_string] => Mauvais traitements envers les personne âgées
            [language_code] => fr

        )

    [12] => Array
        (
            [term_string] => Négligence envers les personnes âgées
            [language_code] => fr

        )

    [13] => Array
        (
            [term_string] => Violence envers les personnes âgées
            [language_code] => fr

        )

    [14] => Array
        (
            [term_string] => Violence envers une personne âgée
            [language_code] => fr

        )

    [15] => Array
        (
            [term_string] => Violence et négligence à l'égard des personne âgées
            [language_code] => fr

        )

    [16] => Array
        (
            [term_string] => Abandono de Idosos
            [language_code] => pt-br

        )

    [17] => Array
        (
            [term_string] => Abuso do Idoso
            [language_code] => pt-br

        )

    [18] => Array
        (
            [term_string] => Maus-Tratos do Idoso
            [language_code] => pt-br

        )

    [19] => Array
        (
            [term_string] => Negligência com o Idoso
            [language_code] => pt-br

        )

)

**Comment by wilsonmoura** [comment]
@arthurtreuherz Estou fazendo testes no portal do DeCS. Por isso apareceu esse código quando você tentou fazer pesquisa.
