### ISSUE TITLE
Erro ao pesquisar qualificadores no índice "Qualquer qualificador"

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#75]
@wilsonmoura a pesquisa de alguns qualificadores (no índice de "Qualquer qualificador") na instância teste, estão dando erro, isto é, não estão recuperando nada e a tela fica um pouco estranha, vazia. Por exemplo, pesquise "anormalidades", ou "deficiencia" e compare com a mesma pesquisa na instância pública.

**Comment by wilsonmoura** [comment]
@arthurtreuherz resolvido em #77

**Comment by arthurtreuherz** [comment]
valeu Wilson.

________________________________
De: Wilson da Silva Moura ***@***.***>
Enviado: sexta-feira, 14 de maio de 2021 15:20
Para: bireme/thesaurus-wp-plugin ***@***.***>
Cc: Treuherz, Arthur (BIR) ***@***.***>; Mention ***@***.***>
Assunto: Re: [bireme/thesaurus-wp-plugin] Erro ao pesquisar qualificadores no índice "Qualquer qualificador" (#75)


@arthurtreuherz<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Farthurtreuherz&data=04%7C01%7Ctreuherz%40paho.org%7Cda29045ca7604e4c1a0508d91704f91e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637566132396504959%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=I31wBhSxfKXKFq6kHKDPBNAn1FP%2Fbwp968vA5xoyjsQ%3D&reserved=0> resolvido em #77<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fthesaurus-wp-plugin%2Fissues%2F77&data=04%7C01%7Ctreuherz%40paho.org%7Cda29045ca7604e4c1a0508d91704f91e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637566132396509956%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=5HEpBTc%2FijRyi3Uqi13k59xv7A7Du%2FvD2lSL2ZUdEJI%3D&reserved=0>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbireme%2Fthesaurus-wp-plugin%2Fissues%2F75%23issuecomment-841420065&data=04%7C01%7Ctreuherz%40paho.org%7Cda29045ca7604e4c1a0508d91704f91e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637566132396514943%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Kv54geDd%2FMw0Cbra8WOAqj7MunMLhcjc6H7g5ssVckg%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAGFIN56U6D5UXXQSKVRABILTNVSXJANCNFSM44DVOXOQ&data=04%7C01%7Ctreuherz%40paho.org%7Cda29045ca7604e4c1a0508d91704f91e%7Ce610e79c2ec04e0f8a141e4b101519f7%7C0%7C0%7C637566132396519933%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7XF8gVF9v11vBnoctJhF0nigjiRLq3mGmxFJ2EseSi0%3D&reserved=0>.

IMPORTANT: This transmission is for use by the intended recipient and it may contain privileged, proprietary or confidential information. If you are not the intended recipient or a person responsible for delivering this transmission to the intended recipient, you may not disclose, copy or distribute this transmission or take any action in reliance on it. If you received this transmission in error, please dispose of and delete this transmission. Thank you.
