### ISSUE TITLE
Erro ao mudar idioma da interface

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/thesaurus-wp-plugin#76]
Na tela de detalhe do termo, como por exemplo

https://decs.bvsalud.org/ths/resource/?id=50343&filter=ths_exact_term&q=Estudos%20Populacionais%20em%20Sa%C3%BAde%20P%C3%BAblica

Se altero o idioma do português para o espanhol, funciona bem.

Entretanto, ao visualizar outro termo, como por exemplo

https://decs.bvsalud.org/ths/resource/?id=28446&filter=ths_exact_term&q=saude%20ambiental

Ao alterar o idioma, apresenta o seguinte erro 

![image](https://user-images.githubusercontent.com/1226218/117837348-c14ad700-b24f-11eb-90d5-99048f60af3a.png)

Só ocorre em espanhol. Não consegui reproduzir com outros termos e tampouco consegui identificar o motivo.

**Comment by wilsonmoura** [comment]
@renatomurasaki o cache dessa página foi gerado novamente. Favor validar.

**Comment by renatomurasaki** [comment]
@wilsonmoura funcionou! O comportamento não seria carregar corretamente a página e depois guardá-la em cache?

**Comment by wilsonmoura** [comment]
@renatomurasaki provavelmente houve algum erro no envio de resposta da API durante o carregamento dessa página. Vale reforçar que o cache está sendo gerado novamente, pois tivemos que limpar o cache antigo para exibir novos campos na página de detalhe.
