### ISSUE TITLE
Não está funcionando o link presente no qualificador de um descritor

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/thesaurus-wp-plugin#77]
Exemplo:

Clicar em qualquer um dos qualificadores do seguinte termo

https://decs.bvsalud.org/es/ths/resource/?id=56928&filter=ths_termall&q=sars

A tela que se abre é

![image](https://user-images.githubusercontent.com/1226218/117863061-bd2bb300-b269-11eb-87f0-4dc34e1677f8.png)

Esse problema parece ocorrer para qualquer descritor.

**Comment by wilsonmoura** [comment]
@renatomurasaki ajuste realizado. Favor validar.

**Comment by renatomurasaki** [comment]
@wilsonmoura funcionando agora. Obrigado!
