### ISSUE TITLE
Ajuste na estratégia do campo Documentos indexados na BVS para qualificadores, alterando o índice de mh para sh

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#78]
Quando o usuário encontra o registro, a estratégia de busca deve usar o índice sh em vez de mh.

Por exemplo, quando o usuário pesquisa https://decs.bvsalud.org/ths/resource/?id=22005&filter=ths_qualifall&q=anormalidades e depois clica no hyperlink de Documentos indexados na BVS, ele cria a estratégia mh:("anormalidades") e não tá encontrando nada.

Mas se a estratégia for sh:("anormalidades") encontra. 

É que sh é a abreviatura de qualificador em inglês (SubHeading).

**Comment by wilsonmoura** [comment]
@arthurtreuherz resolvido no ambiente de testes. No ambiente de produção, vamos ter que solicitar uma nova limpeza de cache do site para exibir esse ajuste.
