### ISSUE TITLE
Incluir a ação farmacológica nos descritores de compostos químicos e drogas

### ISSUE THREAD

**Issue by suelisuga** [bireme/thesaurus-wp-plugin#80]
Solicito inclusão da Ação Farmacológica (AF) nos descritores da categoria de Compostos químicos e drogas no portal do DeCS.

Essa informação é fundamental para a indexação de documentos e há bibliotecários que não utilizam o FI-Admin, porém consultam o DeCS no portal.

No DeCS:
![image](https://user-images.githubusercontent.com/13105683/120242533-72cf9d80-c23b-11eb-9b46-6a54de0efab6.png)

No FI-Admin:
![image](https://user-images.githubusercontent.com/13105683/120242619-b0ccc180-c23b-11eb-9f89-a1cf3c1f7917.png)

Muito obrigada!

**Comment by wilsonmoura** [comment]
@suelisuga essa atividade será implementada em bireme/Gestao-DeCS#49

**Comment by suelisuga** [comment]
Obrigada @wilsonmoura
