### ISSUE TITLE
Ocultar linha reservada para o campo da nota de indexação do DeCS quando o registro não tem esse campo

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#82]
Favor ocultar a linha do campo de nota de indexação (e qq outro campo) na visualização do registro DeCS, quando o registro não possui esse campo. Exemplo:

![image](https://user-images.githubusercontent.com/25855735/122125244-9c292580-ce06-11eb-916a-2072cf63cb80.png)

**Comment by wilsonmoura** [comment]
@arthurtreuherz ajustes realizados. Depende agora de atualização de cache no ambiente de produção (cerca de 4 dias).
