### ISSUE TITLE
Verificar erro em 3 registros

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#85]
Favor verificar os seguintes registros que ainda aparecem "sem tradução" nos 4 idiomas:

https://decs.bvsalud.org/ths/resource/?id=3320&filter=ths_exact_term&q=Comportamento%20Cooperativo

https://decs.bvsalud.org/ths/resource/?id=28566&filter=ths_exact_term&q=Epidemiologia

https://decs.bvsalud.org/ths/resource/?id=3173&filter=ths_exact_term&q=Comunica%C3%A7%C3%A3o

**Comment by wilsonmoura** [comment]
@arthurtreuherz todos esses registros estavam no cache antigo. Conversei com o Anderson e ele atualizou o cache específico dessas páginas que você mencionou. Favor verificar novamente.

**Comment by arthurtreuherz** [comment]
Wilson, realmente, agora parece que está tudo bem. Obrigado
