### ISSUE TITLE
Bug ao buscar pelo descritor "Qualidade do Solo" - não mostra nada

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#86]
Usuária alerta: "Pesquisando no DeCS localizei o descritor 'Qualidade do solo", porém, ao seleciná-lo, a tela aberta está em branco. Poderiam verificar?"

Wilson, não consegui identificar o problema. O descritor existe. Por isso, solicito o seu apoio.

**Comment by wilsonmoura** [comment]
@arthurtreuherz ambiente de testes atualizado. Favor validar. Aguardando atualização do ambiente de produção.

**Comment by arthurtreuherz** [comment]
No ambiente de testes ficou bom. Obrigado. validado.

**Comment by wilsonmoura** [comment]
@arthurtreuherz ambiente de produção atualizado. Favor validar.

**Comment by arthurtreuherz** [comment]
Aprovado. Obrigado!!

**Comment by wilsonmoura** [comment]
Realizado em https://github.com/bireme/fi-admin/pull/1254
