### ISSUE TITLE
Copiar o conteúdo da nota histórica e online do MeSH para visualização em todas as interfaces do DeCS

### ISSUE THREAD

**Issue by arthurtreuherz** [bireme/thesaurus-wp-plugin#87]

**Comment by wilsonmoura** [comment]
@acecampos essa demanda ainda é necessária? Caso contrário, podemos encerrar esse issue?

**Comment by acecampos** [comment]
@wilsonmoura essa demanda ainda persiste.

**Comment by wilsonmoura** [comment]
@acecampos por favor, poderia dar mais detalhes sobre essa demanda?

**Comment by acecampos** [comment]
@wilsonmoura A demanda se refere às notas que aparecem no Fi-Admin (vindas pelo carregamento do MSH) e que não aparecem no site público.
Por exemplo, o registro do descritor [**Isquemia Miocárdica**](https://fi-admin.bvsalud.org/thesaurus/descriptors/view/142434?ths=1)  no Fi-Admin (parte superior) e no site público (parte inferior) na figura abaixo:
![image](https://user-images.githubusercontent.com/35345406/210095516-3c1ceb38-1fa7-4d10-81a4-7d466bd74e3b.png)

**Comment by wilsonmoura** [comment]
@acecampos nesse exemplo do comentário anterior, as notas já estão disponíveis no portal (veja imagem), mas apenas no idioma que estão cadastradas (nesse caso, no idioma inglês). Para que as notas sejam exibidas nos outros idiomas, é necessário realizar o cadastro do respectivo idioma no sistema FI-ADMIN.

![screenshot-decs teste bvs br-2023 01 02-17_46_47](https://user-images.githubusercontent.com/3779520/210276916-f86c95a8-89d3-4928-b163-9fa2c88a5007.png)

**Comment by acecampos** [comment]
Entendi, @wilsonmoura. Obrigada!
