### ISSUE TITLE
Criar página no site do DeCS para divulgar a vaga de analista de informação

### ISSUE THREAD

**Issue by renatomurasaki** [bireme/thesaurus-wp-plugin#88]
@acecampos por favor, utilizar a informação que lhe enviei por e-mail com os ToR da vaga. Proposta de estrutura da página:

0) Título: Oportunidade de trabalho: analista de informação na área de terminologias em saúde
1) Quem somos? (um parágrafo sobre a BIREME)
2) Terminologias em Ciências da Saúde (um parágrafo sobre o DeCS/MeSH e a responsabilidade da BIREME)
3) Oportunidade de trabalho como Analista de Informação
  3.1) Objetivo da vaga
  3.2) Resumo das responsabilidades
  3.3) (incluir as demais seções do ToR
4) Modalidade de contratação: CLT (salário a combinar)
5) Se você quer fazer parte da equipe de Terminologias em Ciências da Saúde da BIREME/OPAS/OMS, envie seu CV para (...)

Podemos colocar o e-mail institucional da área?

Edite o slug para ficar como vaga-analista-informacao-2021

**Comment by acecampos** [comment]
@renatomurasaki acho oportuno, sim, colocar o e-mail institucional da área, ao qual o Arthur também tem acesso. Preparo da página em andamento.

**Comment by acecampos** [comment]
@renatomurasaki por favor, avalie o http://decs.bvsalud.org/vaga-analista-informacao-2021/. Grata

**Comment by renatomurasaki** [comment]
@acecampos o link está dando erro 404

**Comment by acecampos** [comment]
https://decs.bvsalud.org/vaga-analista-informacao-2021/
Desculpe, @renatomurasaki. Estava em modo rascunho. Agora testei nos outros navegadores e o link funcionou.

**Comment by renatomurasaki** [comment]
@acecampos está muito bom. Sugestões:

- Deixar os títulos em cor preta, porque o uso de azul é em geral usado para links. Mantê-los em negrito. Se puder aumentar o tamanho da letra seria melhor.
- Deixar em negrito os títulos dos subitens 3
- Acho que seria bom deixar o texto "Se você quer fazer parte da equipe de Terminologias em Ciências da Saúde da BIREME/OPAS/OMS, envie seu CV para bir.decs@paho.org." em destaque. Converse com o Márcio para ideias.

**Comment by acecampos** [comment]
@renatomurasaki Após conversa com Márcio, por favor validar as alterações https://decs.bvsalud.org/vaga-analista-informacao-2021. Grata.

**Comment by renatomurasaki** [comment]
@acecampos @marcioalvessilva excelente. O que acham de colocar o nome dos subitens abaixo em negrito:

3.1. Objetivo da vaga:
3.2. Resumo das responsabilidades:
3.3. Competências:
3.4. Habilidades:
3.5. Educação:
3.6. Experiência:
3.7. Idiomas:
3.8. Conhecimentos em tecnologia da informação:
3.9. Modalidade de contratação: 

Creio que o texto

3.10. Se você quer fazer parte da equipe de Terminologias em Ciências da Saúde da BIREME/OPAS/OMS (...)

Pode ficar como um parágrafo sem ser o subitem 3.10

**Comment by acecampos** [comment]
@renatomurasaki Ok, Feito:  https://decs.bvsalud.org/vaga-analista-informacao-2021/

**Comment by arthurtreuherz** [comment]
Excelente Renato e Ana.

**Comment by renatomurasaki** [comment]
@acecampos obrigado. Está ótimo!
