### ISSUE TITLE
Verificar a utilização do asterisco para poder pesquisar radical

### ISSUE THREAD

**Issue by falbrito** [bireme/thesaurus-wp-plugin#9]
Verificar a utilização do asterisco para poder pesquisar radical.
exemplo: Para pesquisar tudo o que começa com febr*

atualmente retorna somente 1 resultado e esperasse que traga resultado para febre

**Comment by renatomurasaki** [comment]
Além disso, avaliar se também deveríamos explicitar uma opção de busca permutada

**Comment by falbrito** [comment]
Relacionado ao issue #23
