### ISSUE TITLE
Botão para ver espanhol da Espanha na página de recuperação do DeCS

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#90]
Wilson, bom dia!
Conforme sugestão do Renato durante a reunião com ISCIII, em 29set21, solicito criar um botão para mostrar na página de recuperação de resultados os descritores e sinônimos no espanhol da Espanha.

O botão ficaria na linha do descritor em espanhol e ficaria aberto quando o usuário clicasse nele como uma caixa, conforme simulado nas figuras anexadas, mostrando o descritor e o(s) sinônimo(s) no espanhol da Espanha. O diferencial seria mostrar em letras iniciais minúsculas mesmo, já que a Espanha vem fazendo assim há muitos anos.

Grata!
![espanol de Espana con ejemplo en el portal](https://user-images.githubusercontent.com/35345406/138460809-5c7d8d44-5f5a-4f2a-a6d3-6e4110916cf5.jpg)
![espanol de Espana en el portal](https://user-images.githubusercontent.com/35345406/138460816-5df7087d-4a9b-472a-904e-fb5c7a608d7a.jpg)

**Comment by acecampos** [comment]
Favor proceder da mesma forma com o campo de Scope Note / **Nota de Alcance** / Nota de Escopo para mostrar a nota de alcance do espanhol da Espanha também.

**Comment by marcioalvessilva** [comment]
Segue link de proposta
http://mockups.teste.bireme.org/decs/resource.php

**Comment by acecampos** [comment]
A fim de não poluir muito visualmente, concordo com Wilson em deixar a nota de alcance no mesmo quadro do descritor e dos sinônimos. Mas se houver outra possibilidade de visualização diferente, estou à disposição para discutir... e votar.

**Comment by wilsonmoura** [comment]
@acecampos ajustes realizados no ambiente de testes. Favor validar.

**Comment by acecampos** [comment]
@wilsonmoura validado.
