### ISSUE TITLE
Incluir nova categoria para hierarquia de MTCI no DeCS

### ISSUE THREAD

**Issue by wilsonmoura** [bireme/thesaurus-wp-plugin#91]

**Comment by acecampos** [comment]
@wilsonmoura não sei qual é o ambiente de testes nesse caso. Pode me indicar, por favor?

**Comment by wilsonmoura** [comment]
@acecampos o ambiente de testes do DeCS é https://decs.teste.bvs.br

**Comment by acecampos** [comment]
Obrigada, @wilsonmoura 
Eu estava colocando bvsalud...

**Comment by acecampos** [comment]
@wilsonmoura VALIDADO! Obrigada.
