### ISSUE TITLE
Falha na recuperação por termo alternativo

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#92]
@wilsonmoura Bom dia! Recebemos a seguinte mensagem de usuário no Livezilla:

"Por que alguns termos alternativos são buscados diretamente no buscador do DeCS, como "saúde coletiva", e outros não são buscados diretamente, como "práticas corporais"? O termo práticas corporais pode ser encontrado se buscamos o descritor "Manipulações Musculoesqueléticas", ou seja, apenas em busca indireta. Vide https://decs.bvsalud.org/ths/resource/?id=36279&filter=ths_termall&q=manipula%C3%A7%C3%B5es%20musculoesquel%C3%A9ticas"

![image](https://user-images.githubusercontent.com/35345406/159916516-d27f76a2-7bc2-4d20-ab33-501ec19fc21b.png)

A @lucianaPRB fez o teste e realmente "Práticas Corporais" não é recuperado na busca por _Qualquer termo_ na página inicial do decs.bvsalud.org.

Você pode verificar, por favor?
É um problema de resolução para agora ou só a partir da edição 2022 no ar?

Agradecemos!

**Comment by wilsonmoura** [comment]
@acecampos creio que o índice referente ao DeCS 2021 estava corrompido em algum ponto específico. Estamos preparando o novo índice para o lançamento do DeCS 2022, e o mesmo já está disponível para testes em https://decs.teste.bvs.br

**Comment by acecampos** [comment]
@wilsonmoura Validado no ambiente de testes. Obrigada!
