### ISSUE TITLE
Quantificação de novos termos 2022 por data de entrada

### ISSUE THREAD

**Issue by acecampos** [bireme/thesaurus-wp-plugin#95]
@wilsonmoura por favor, pode preparar um relatório de termos por **data de entrada** no Fi-Admin? Período: entre 25 de maio de 2021 e 31 de maio de 2022.

Esse dado será usado na página de novidades de 2022.

Seriam os seguintes dados nas colunas:
TermUI | Language | Term Type | String | Tree | Date

Gratas!
AnaLu
@lucianaPRB

**Comment by wilsonmoura** [comment]
@acecampos segue arquivo solicitado com os registros: [dbeaver_202207051928.txt](https://github.com/bireme/thesaurus-wp-plugin/files/9050040/dbeaver_202207051928.txt)

**Comment by acecampos** [comment]
Ok, obrigada!

**Comment by wilsonmoura** [comment]
Query usada nessa consulta:
```
select
	a.term_ui,
	a.language_code,
	a.term_string,
	d.tree_number,
	a.date_created,
	(CASE
		WHEN a.concept_preferred_term='Y' && a.record_preferred_term='Y' THEN 'MH'
		WHEN a.concept_preferred_term='Y' && a.record_preferred_term='N' THEN 'PEP'
		ELSE 'ET'
	END) as term_type
from
	thesaurus_termlistdesc as a, 
	thesaurus_identifierconceptlistdesc as b, 
	thesaurus_identifierdesc as c,
	thesaurus_treenumberslistdesc as d
where
	a.term_thesaurus='1' and
	a.status='1' and
	a.identifier_concept_id=b.id and
	b.identifier_id=c.id and
	d.identifier_id=c.id and
	c.date_created BETWEEN '2021-05-25' AND '2022-05-31'
```
