### ISSUE TITLE
Retirar URI de RDF NLM - Qualificador exclusivo DeCS 

### ISSUE THREAD

**Issue by lucianaPRB** [bireme/thesaurus-wp-plugin#96]
Retirar se possível, exclusivamente, o URI que levaria ao RDF da NLM do registro do qualificador QDCS022082, por ser exclusivo DeCS o link leva a uma página de erro. Conforme imagem:
![QDCS022082](https://user-images.githubusercontent.com/93340661/179076986-acc1dfa4-bbf7-43ab-8803-631ae5bbfe3f.PNG)

![WhatsApp Image 2022-07-14 at 17 01 25](https://user-images.githubusercontent.com/93340661/179077130-e31f7871-3a0d-4953-a2cd-ddef0394ca11.jpeg)

Agradeço,

**Comment by wilsonmoura** [comment]
@lucianaPRB ajustes realizados no ambiente de testes. Favor validar.

**Comment by lucianaPRB** [comment]
Wilson, continua aparecendo o link como estava. Será que olhei no lugar errado?

![image](https://user-images.githubusercontent.com/93340661/183977585-db18af2c-7b80-4668-8282-9d3355d3d54f.png)

**Comment by wilsonmoura** [comment]
@lucianaPRB favor validar no ambiente de testes: https://decs.teste.bvs.br

**Comment by lucianaPRB** [comment]
validado, @wilsonmoura! Muito obrigada
