### ISSUE TITLE
Inserir filtros para ordenar resultados

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/thesaurus-wp-plugin#97]
Boa tarde!
**Analisar** a possibilidade de inserir filtros para ordenar resultados por relevância e permitir a troca para organizar por ordem alfabética

Exemplo de busca  por câncer 171 resultados
![image](https://user-images.githubusercontent.com/48724136/195893624-f3ba2e34-e743-4525-b95a-331f4aae97fc.png)

Caso seja possível vou pensar onde inserir o campo para troca.
Grato!

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by marcioalvessilva** [comment]
Recurso a aprovado pela @acecampos.
Ajuste
- No primeiro carregamento, trazer o resultado por relevância e permitir a troca por ordem alfabética.
- incluir a class "btn-sm" no botão

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by marcioalvessilva** [comment]
Legal @wilsonmoura vou finalizar o issue e mandar um e-mail para equipe do DeCS autorizar enviar para produção.
Grato!
