### ISSUE TITLE
Expandir árvore dentro da estrutura hierárquica

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/thesaurus-wp-plugin#98]
Boa tarde!
**Analisar**  se é possível inserir o recurso de expandir árvore hierárquica quando clicar nos sinais e "+" permitindo não sair do resultado
![image](https://user-images.githubusercontent.com/48724136/195894471-edc304e4-d455-47f5-9a68-f0c40ae918b3.png)

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by marcioalvessilva** [comment]
Concluído!
