### ISSUE TITLE
Ajuste de bug na página de Visão Hierárquica 

### ISSUE THREAD

**Issue by marcioalvessilva** [bireme/thesaurus-wp-plugin#99]
Analisar possibilidade de correção de bug que acontece quando expande duas áreas ao mesmo tempo.
![image](https://user-images.githubusercontent.com/48724136/195895837-16af4c02-33c3-4a3a-a6f6-9fdeacd66515.png)

**Comment by wilsonmoura** [comment]
@marcioalvessilva ajustes realizados. Favor validar no ambiente de testes do Portal DeCS.

**Comment by marcioalvessilva** [comment]
Concluído!
